//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsirk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string comment { get; set; }
        public byte is_close { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
